# Generated by Django 5.1.15 on 2026-05-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testplan",
            name="plan_type",
            field=models.CharField(
                choices=[("qa", "QA Testing"), ("security", "Security Testing")],
                default="qa",
                max_length=10,
            ),
        ),
    ]
