# Generated by Django 5.1.15 on 2026-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_finding"),
    ]

    operations = [
        migrations.AddField(
            model_name="teststep",
            name="section",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Grouping category for organizing large test plans (e.g. Authentication, Dashboard, Reports)",
                max_length=255,
            ),
        ),
    ]
