# Generated by Django 5.1.15 on 2026-10-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_teststep_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runstepresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("blocked", "Blocked"),
                ],
                max_length=10,
            ),
        ),
    ]
