# Generated by Django 5.1.15 on 2026-10-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_runstepresult_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="step_ids",
            field=models.ManyToManyField(
                blank=True, related_name="findings", to="core.teststep"
            ),
        ),
    ]
